function(e,s,r,gg){
var z=gz$gwx_2()
var tEB=_n('view')
_rz(z,tEB,'class',0,e,s,gg)
var eFB=_mz(z,'image',['class',1,'mode',1,'src',2],[],e,s,gg)
_(tEB,eFB)
var bGB=_n('view')
_rz(z,bGB,'style',4,e,s,gg)
var oHB=_n('view')
_rz(z,oHB,'class',5,e,s,gg)
var xIB=_n('view')
_rz(z,xIB,'class',6,e,s,gg)
var oJB=_oz(z,7,e,s,gg)
_(xIB,oJB)
_(oHB,xIB)
var fKB=_n('view')
_rz(z,fKB,'class',8,e,s,gg)
var cLB=_oz(z,9,e,s,gg)
_(fKB,cLB)
_(oHB,fKB)
_(bGB,oHB)
var hMB=_n('view')
_rz(z,hMB,'class',10,e,s,gg)
var oNB=_n('view')
_rz(z,oNB,'class',11,e,s,gg)
var cOB=_oz(z,12,e,s,gg)
_(oNB,cOB)
_(hMB,oNB)
var oPB=_n('view')
_rz(z,oPB,'class',13,e,s,gg)
var lQB=_oz(z,14,e,s,gg)
_(oPB,lQB)
_(hMB,oPB)
_(bGB,hMB)
var aRB=_n('view')
_rz(z,aRB,'class',15,e,s,gg)
var tSB=_n('view')
_rz(z,tSB,'class',16,e,s,gg)
var eTB=_oz(z,17,e,s,gg)
_(tSB,eTB)
_(aRB,tSB)
var bUB=_n('view')
_rz(z,bUB,'class',18,e,s,gg)
var oVB=_oz(z,19,e,s,gg)
_(bUB,oVB)
_(aRB,bUB)
_(bGB,aRB)
var xWB=_n('view')
_rz(z,xWB,'class',20,e,s,gg)
var oXB=_n('view')
_rz(z,oXB,'class',21,e,s,gg)
var fYB=_oz(z,22,e,s,gg)
_(oXB,fYB)
_(xWB,oXB)
var cZB=_n('view')
_rz(z,cZB,'class',23,e,s,gg)
var h1B=_oz(z,24,e,s,gg)
_(cZB,h1B)
_(xWB,cZB)
_(bGB,xWB)
var o2B=_n('view')
_rz(z,o2B,'class',25,e,s,gg)
var c3B=_n('view')
_rz(z,c3B,'class',26,e,s,gg)
var o4B=_oz(z,27,e,s,gg)
_(c3B,o4B)
_(o2B,c3B)
var l5B=_n('view')
_rz(z,l5B,'class',28,e,s,gg)
var a6B=_oz(z,29,e,s,gg)
_(l5B,a6B)
_(o2B,l5B)
_(bGB,o2B)
var t7B=_n('view')
_rz(z,t7B,'class',30,e,s,gg)
var e8B=_n('view')
_rz(z,e8B,'class',31,e,s,gg)
var b9B=_oz(z,32,e,s,gg)
_(e8B,b9B)
_(t7B,e8B)
var o0B=_n('view')
_rz(z,o0B,'class',33,e,s,gg)
var xAC=_oz(z,34,e,s,gg)
_(o0B,xAC)
_(t7B,o0B)
_(bGB,t7B)
var oBC=_n('view')
_rz(z,oBC,'class',35,e,s,gg)
var fCC=_n('view')
_rz(z,fCC,'class',36,e,s,gg)
var cDC=_oz(z,37,e,s,gg)
_(fCC,cDC)
_(oBC,fCC)
var hEC=_n('view')
_rz(z,hEC,'class',38,e,s,gg)
var oFC=_oz(z,39,e,s,gg)
_(hEC,oFC)
_(oBC,hEC)
_(bGB,oBC)
var cGC=_n('view')
_rz(z,cGC,'class',40,e,s,gg)
var oHC=_n('view')
_rz(z,oHC,'class',41,e,s,gg)
var lIC=_oz(z,42,e,s,gg)
_(oHC,lIC)
_(cGC,oHC)
var aJC=_n('view')
_rz(z,aJC,'class',43,e,s,gg)
var tKC=_oz(z,44,e,s,gg)
_(aJC,tKC)
_(cGC,aJC)
_(bGB,cGC)
_(tEB,bGB)
var eLC=_mz(z,'button',['bindtap',45,'class',1],[],e,s,gg)
var bMC=_oz(z,47,e,s,gg)
_(eLC,bMC)
_(tEB,eLC)
var oNC=_mz(z,'button',['class',48,'openType',1],[],e,s,gg)
var xOC=_oz(z,50,e,s,gg)
_(oNC,xOC)
_(tEB,oNC)
_(r,tEB)
return r
}