function(e,s,r,gg){
var z=gz$gwx_5()
var b7D=_n('view')
_rz(z,b7D,'class',0,e,s,gg)
var o8D=_mz(z,'form',['bindreset',1,'bindsubmit',1],[],e,s,gg)
var x9D=_mz(z,'textarea',['class',3,'disabled',1,'name',2,'value',3],[],e,s,gg)
var o0D=_oz(z,7,e,s,gg)
_(x9D,o0D)
_(o8D,x9D)
var fAE=_n('text')
var cBE=_oz(z,8,e,s,gg)
_(fAE,cBE)
_(o8D,fAE)
var hCE=_mz(z,'button',['bindtap',9,'class',1,'id',2],[],e,s,gg)
var oDE=_oz(z,12,e,s,gg)
_(hCE,oDE)
_(o8D,hCE)
var cEE=_n('checkbox-group')
_rz(z,cEE,'name',13,e,s,gg)
var oFE=_v()
_(cEE,oFE)
var lGE=function(tIE,aHE,eJE,gg){
var oLE=_n('view')
var xME=_n('label')
var oNE=_n('checkbox')
_rz(z,oNE,'value',16,tIE,aHE,gg)
_(xME,oNE)
var fOE=_oz(z,17,tIE,aHE,gg)
_(xME,fOE)
_(oLE,xME)
_(eJE,oLE)
return eJE
}
oFE.wxXCkey=2
_2z(z,14,lGE,e,s,gg,oFE,'item','index','{{index}}')
_(o8D,cEE)
var cPE=_oz(z,18,e,s,gg)
_(o8D,cPE)
var hQE=_mz(z,'textarea',['class',19,'name',1],[],e,s,gg)
_(o8D,hQE)
var oRE=_n('view')
_rz(z,oRE,'class',21,e,s,gg)
var cSE=_mz(z,'button',['formType',22,'style',1],[],e,s,gg)
var oTE=_oz(z,24,e,s,gg)
_(cSE,oTE)
_(oRE,cSE)
var lUE=_mz(z,'button',['formType',25,'style',1],[],e,s,gg)
var aVE=_oz(z,27,e,s,gg)
_(lUE,aVE)
_(oRE,lUE)
_(o8D,oRE)
_(b7D,o8D)
_(r,b7D)
return r
}