function(e,s,r,gg){
var z=gz$gwx_6()
var eXE=_n('view')
_rz(z,eXE,'class',0,e,s,gg)
var bYE=_mz(z,'image',['class',1,'mode',1,'src',2],[],e,s,gg)
_(eXE,bYE)
var oZE=_n('text')
_rz(z,oZE,'class',4,e,s,gg)
var x1E=_oz(z,5,e,s,gg)
_(oZE,x1E)
_(eXE,oZE)
var o2E=_n('view')
var f3E=_mz(z,'form',['bindreset',6,'bindsubmit',1,'reportSubmit',2],[],e,s,gg)
var c4E=_n('view')
_rz(z,c4E,'class',9,e,s,gg)
var h5E=_n('view')
_rz(z,h5E,'style',10,e,s,gg)
var o6E=_oz(z,11,e,s,gg)
_(h5E,o6E)
var c7E=_mz(z,'input',['class',12,'name',1,'placeholder',2,'value',3],[],e,s,gg)
_(h5E,c7E)
_(c4E,h5E)
var o8E=_mz(z,'view',['class',16,'style',1],[],e,s,gg)
var l9E=_oz(z,18,e,s,gg)
_(o8E,l9E)
var a0E=_mz(z,'input',['class',19,'name',1,'password',2,'placeholder',3,'value',4],[],e,s,gg)
_(o8E,a0E)
_(c4E,o8E)
_(f3E,c4E)
var tAF=_n('view')
_rz(z,tAF,'class',24,e,s,gg)
var eBF=_mz(z,'button',['class',25,'formType',1,'reportSubmit',2],[],e,s,gg)
var bCF=_oz(z,28,e,s,gg)
_(eBF,bCF)
_(tAF,eBF)
_(f3E,tAF)
_(o2E,f3E)
_(eXE,o2E)
_(r,eXE)
var oDF=_n('view')
_rz(z,oDF,'style',29,e,s,gg)
var xEF=_mz(z,'view',['bindtap',30,'style',1],[],e,s,gg)
var oFF=_oz(z,32,e,s,gg)
_(xEF,oFF)
_(oDF,xEF)
var fGF=_mz(z,'view',['bindtap',33,'style',1],[],e,s,gg)
var cHF=_oz(z,35,e,s,gg)
_(fGF,cHF)
_(oDF,fGF)
_(r,oDF)
return r
}