function(e,s,r,gg){
var z=gz$gwx_7()
var oJF=_n('view')
_rz(z,oJF,'class',0,e,s,gg)
var cKF=_mz(z,'image',['class',1,'mode',1,'src',2],[],e,s,gg)
_(oJF,cKF)
var oLF=_n('view')
_rz(z,oLF,'class',4,e,s,gg)
var lMF=_n('text')
var aNF=_oz(z,5,e,s,gg)
_(lMF,aNF)
_(oLF,lMF)
_(oJF,oLF)
var tOF=_n('view')
_rz(z,tOF,'class',6,e,s,gg)
var ePF=_oz(z,7,e,s,gg)
_(tOF,ePF)
_(oJF,tOF)
var bQF=_n('view')
_rz(z,bQF,'bindtap',8,e,s,gg)
var oRF=_mz(z,'image',['class',9,'src',1],[],e,s,gg)
_(bQF,oRF)
var xSF=_n('text')
_rz(z,xSF,'class',11,e,s,gg)
var oTF=_oz(z,12,e,s,gg)
_(xSF,oTF)
_(bQF,xSF)
_(oJF,bQF)
var fUF=_n('view')
_rz(z,fUF,'bindtap',13,e,s,gg)
var cVF=_mz(z,'image',['class',14,'src',1],[],e,s,gg)
_(fUF,cVF)
var hWF=_n('text')
_rz(z,hWF,'class',16,e,s,gg)
var oXF=_oz(z,17,e,s,gg)
_(hWF,oXF)
_(fUF,hWF)
_(oJF,fUF)
var cYF=_n('view')
_rz(z,cYF,'bindtap',18,e,s,gg)
var oZF=_mz(z,'image',['class',19,'src',1],[],e,s,gg)
_(cYF,oZF)
var l1F=_n('text')
_rz(z,l1F,'class',21,e,s,gg)
var a2F=_oz(z,22,e,s,gg)
_(l1F,a2F)
_(cYF,l1F)
_(oJF,cYF)
var t3F=_n('view')
_rz(z,t3F,'bindtap',23,e,s,gg)
var e4F=_mz(z,'image',['class',24,'src',1],[],e,s,gg)
_(t3F,e4F)
var b5F=_n('text')
_rz(z,b5F,'class',26,e,s,gg)
var o6F=_oz(z,27,e,s,gg)
_(b5F,o6F)
_(t3F,b5F)
_(oJF,t3F)
_(r,oJF)
return r
}