function(e,s,r,gg){
var z=gz$gwx_8()
var o8F=_n('view')
_rz(z,o8F,'style',0,e,s,gg)
var f9F=_mz(z,'form',['bindreset',1,'bindsubmit',1],[],e,s,gg)
var c0F=_n('view')
_rz(z,c0F,'style',3,e,s,gg)
var hAG=_oz(z,4,e,s,gg)
_(c0F,hAG)
var oBG=_mz(z,'input',['class',5,'name',1,'placeholder',2],[],e,s,gg)
_(c0F,oBG)
_(f9F,c0F)
var cCG=_n('view')
_rz(z,cCG,'style',8,e,s,gg)
var oDG=_oz(z,9,e,s,gg)
_(cCG,oDG)
var lEG=_mz(z,'input',['class',10,'name',1,'placeholder',2],[],e,s,gg)
_(cCG,lEG)
_(f9F,cCG)
var aFG=_n('view')
_rz(z,aFG,'style',13,e,s,gg)
var tGG=_oz(z,14,e,s,gg)
_(aFG,tGG)
var eHG=_mz(z,'input',['class',15,'name',1,'placeholder',2],[],e,s,gg)
_(aFG,eHG)
_(f9F,aFG)
var bIG=_n('view')
_rz(z,bIG,'style',18,e,s,gg)
var oJG=_oz(z,19,e,s,gg)
_(bIG,oJG)
var xKG=_mz(z,'input',['class',20,'name',1,'placeholder',2],[],e,s,gg)
_(bIG,xKG)
_(f9F,bIG)
var oLG=_n('view')
_rz(z,oLG,'style',23,e,s,gg)
var fMG=_oz(z,24,e,s,gg)
_(oLG,fMG)
var cNG=_mz(z,'input',['class',25,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(oLG,cNG)
_(f9F,oLG)
var hOG=_n('view')
_rz(z,hOG,'style',29,e,s,gg)
var oPG=_oz(z,30,e,s,gg)
_(hOG,oPG)
var cQG=_mz(z,'input',['class',31,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(hOG,cQG)
_(f9F,hOG)
var oRG=_n('view')
_rz(z,oRG,'style',35,e,s,gg)
var lSG=_oz(z,36,e,s,gg)
_(oRG,lSG)
var aTG=_mz(z,'input',['class',37,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(oRG,aTG)
_(f9F,oRG)
var tUG=_n('view')
_rz(z,tUG,'class',41,e,s,gg)
var eVG=_mz(z,'button',['class',42,'formType',1],[],e,s,gg)
var bWG=_oz(z,44,e,s,gg)
_(eVG,bWG)
_(tUG,eVG)
_(f9F,tUG)
_(o8F,f9F)
_(r,o8F)
return r
}