function(e,s,r,gg){
var z=gz$gwx_9()
var xYG=_n('view')
_rz(z,xYG,'class',0,e,s,gg)
var oZG=_n('view')
_rz(z,oZG,'class',1,e,s,gg)
var f1G=_oz(z,2,e,s,gg)
_(oZG,f1G)
_(xYG,oZG)
var c2G=_mz(z,'image',['class',3,'mode',1,'src',2],[],e,s,gg)
_(xYG,c2G)
var h3G=_mz(z,'form',['bindreset',6,'bindsubmit',1],[],e,s,gg)
var o4G=_n('view')
_rz(z,o4G,'style',8,e,s,gg)
var c5G=_oz(z,9,e,s,gg)
_(o4G,c5G)
var o6G=_mz(z,'input',['class',10,'name',1,'placeholder',2],[],e,s,gg)
_(o4G,o6G)
_(h3G,o4G)
var l7G=_n('view')
_rz(z,l7G,'style',13,e,s,gg)
var a8G=_oz(z,14,e,s,gg)
_(l7G,a8G)
var t9G=_mz(z,'input',['class',15,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(l7G,t9G)
_(h3G,l7G)
var e0G=_n('view')
_rz(z,e0G,'style',19,e,s,gg)
var bAH=_oz(z,20,e,s,gg)
_(e0G,bAH)
var oBH=_mz(z,'input',['class',21,'name',1,'placeholder',2],[],e,s,gg)
_(e0G,oBH)
_(h3G,e0G)
var xCH=_n('view')
_rz(z,xCH,'style',24,e,s,gg)
var oDH=_oz(z,25,e,s,gg)
_(xCH,oDH)
var fEH=_mz(z,'button',['bindtap',26,'style',1],[],e,s,gg)
var cFH=_oz(z,28,e,s,gg)
_(fEH,cFH)
_(xCH,fEH)
_(h3G,xCH)
var hGH=_n('view')
_rz(z,hGH,'class',29,e,s,gg)
var oHH=_mz(z,'button',['formType',30,'style',1],[],e,s,gg)
var cIH=_oz(z,32,e,s,gg)
_(oHH,cIH)
_(hGH,oHH)
_(h3G,hGH)
_(xYG,h3G)
_(r,xYG)
return r
}