function(e,s,r,gg){
var z=gz$gwx_10()
var lKH=_n('view')
_rz(z,lKH,'class',0,e,s,gg)
var aLH=_mz(z,'image',['class',1,'mode',1,'src',2],[],e,s,gg)
_(lKH,aLH)
var tMH=_mz(z,'form',['bindreset',4,'bindsubmit',1,'class',2],[],e,s,gg)
var eNH=_n('view')
_rz(z,eNH,'style',7,e,s,gg)
var bOH=_oz(z,8,e,s,gg)
_(eNH,bOH)
var oPH=_mz(z,'input',['class',9,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(eNH,oPH)
_(tMH,eNH)
var xQH=_n('view')
_rz(z,xQH,'style',13,e,s,gg)
var oRH=_oz(z,14,e,s,gg)
_(xQH,oRH)
var fSH=_mz(z,'input',['class',15,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(xQH,fSH)
_(tMH,xQH)
var cTH=_n('view')
_rz(z,cTH,'style',19,e,s,gg)
var hUH=_oz(z,20,e,s,gg)
_(cTH,hUH)
var oVH=_mz(z,'input',['class',21,'name',1,'password',2,'placeholder',3],[],e,s,gg)
_(cTH,oVH)
_(tMH,cTH)
var cWH=_n('view')
_rz(z,cWH,'style',25,e,s,gg)
var oXH=_oz(z,26,e,s,gg)
_(cWH,oXH)
var lYH=_mz(z,'input',['class',27,'name',1,'password',2,'placeholder',3],[],e,s,gg)
_(cWH,lYH)
_(tMH,cWH)
var aZH=_n('view')
_rz(z,aZH,'class',31,e,s,gg)
var t1H=_mz(z,'button',['formType',32,'style',1],[],e,s,gg)
var e2H=_oz(z,34,e,s,gg)
_(t1H,e2H)
_(aZH,t1H)
_(tMH,aZH)
_(lKH,tMH)
_(r,lKH)
return r
}