function(e,s,r,gg){
var z=gz$gwx_11()
var o4H=_n('view')
_rz(z,o4H,'class',0,e,s,gg)
var x5H=_mz(z,'image',['class',1,'mode',1,'src',2],[],e,s,gg)
_(o4H,x5H)
var o6H=_mz(z,'form',['bindreset',4,'bindsubmit',1],[],e,s,gg)
var f7H=_n('view')
_rz(z,f7H,'style',6,e,s,gg)
var c8H=_oz(z,7,e,s,gg)
_(f7H,c8H)
var h9H=_mz(z,'input',['class',8,'name',1,'placeholder',2],[],e,s,gg)
_(f7H,h9H)
_(o6H,f7H)
var o0H=_mz(z,'view',['name',11,'style',1],[],e,s,gg)
var cAI=_mz(z,'radio-group',['bindchange',13,'class',1,'name',2],[],e,s,gg)
var oBI=_oz(z,16,e,s,gg)
_(cAI,oBI)
var lCI=_v()
_(cAI,lCI)
var aDI=function(eFI,tEI,bGI,gg){
var xII=_mz(z,'label',['class',18,'name',1],[],eFI,tEI,gg)
var oJI=_mz(z,'radio',['checked',20,'name',1,'style',2,'value',3],[],eFI,tEI,gg)
_(xII,oJI)
var fKI=_oz(z,24,eFI,tEI,gg)
_(xII,fKI)
_(bGI,xII)
return bGI
}
lCI.wxXCkey=2
_2z(z,17,aDI,e,s,gg,lCI,'item','index','')
_(o0H,cAI)
_(o6H,o0H)
var cLI=_n('view')
_rz(z,cLI,'style',25,e,s,gg)
var hMI=_oz(z,26,e,s,gg)
_(cLI,hMI)
var oNI=_mz(z,'input',['class',27,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(cLI,oNI)
_(o6H,cLI)
var cOI=_n('view')
_rz(z,cOI,'style',31,e,s,gg)
var oPI=_oz(z,32,e,s,gg)
_(cOI,oPI)
var lQI=_mz(z,'input',['class',33,'name',1,'password',2,'placeholder',3],[],e,s,gg)
_(cOI,lQI)
_(o6H,cOI)
var aRI=_n('view')
_rz(z,aRI,'style',37,e,s,gg)
var tSI=_oz(z,38,e,s,gg)
_(aRI,tSI)
var eTI=_mz(z,'input',['class',39,'name',1,'password',2,'placeholder',3],[],e,s,gg)
_(aRI,eTI)
_(o6H,aRI)
var bUI=_n('view')
_rz(z,bUI,'style',43,e,s,gg)
var oVI=_oz(z,44,e,s,gg)
_(bUI,oVI)
var xWI=_mz(z,'input',['class',45,'name',1,'placeholder',2,'type',3],[],e,s,gg)
_(bUI,xWI)
_(o6H,bUI)
var oXI=_n('view')
_rz(z,oXI,'style',49,e,s,gg)
var fYI=_oz(z,50,e,s,gg)
_(oXI,fYI)
var cZI=_mz(z,'input',['class',51,'name',1,'placeholder',2],[],e,s,gg)
_(oXI,cZI)
_(o6H,oXI)
var h1I=_n('view')
_rz(z,h1I,'class',54,e,s,gg)
var o2I=_mz(z,'button',['formType',55,'style',1],[],e,s,gg)
var c3I=_oz(z,57,e,s,gg)
_(o2I,c3I)
_(h1I,o2I)
_(o6H,h1I)
_(o4H,o6H)
_(r,o4H)
return r
}